source 'https://sugawara_picos@bitbucket.org/sugawara_picos/specs.git'
source 'https://github.com/yusuga/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'YSUIKitAdditions'
